# Copyright (C) 2020-2021 The LineageOS Project
# Copyright (C) 2020-2021 The PixelExperience Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/realme/RMX1851/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RMX1851

PRODUCT_COPY_FILES += \
    vendor/realme/RMX1851/proprietary/lib64/fm_helium.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/fm_helium.so \
    vendor/realme/RMX1851/proprietary/lib64/libfm-hci.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfm-hci.so \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b00:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b00 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b01:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b01 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b02:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b02 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b03:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b03 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b04:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b04 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b05:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b05 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b06:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b06 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.b07:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.b07 \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/firmware/a_fp.mdt:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/firmware/a_fp.mdt \
    vendor/realme/RMX1851/proprietary/product/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libaptXHD_encoder.so \
    vendor/realme/RMX1851/proprietary/product/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libaptX_encoder.so \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/lib/soundfx/libvolumelistener.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib/soundfx/libvolumelistener.so \
    vendor/realme/RMX1851/proprietary/product/vendor_overlay/29/lib64/soundfx/libvolumelistener.so:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/29/lib64/soundfx/libvolumelistener.so

PRODUCT_PACKAGES += \
    vendor.qti.hardware.fm@1.0 \
    PowerOffAlarm
